nelmio_cors:
    defaults:
        allow_origin: ['*']
        allow_headers: ['*']
        allow_methods: ['*']
        max_age: 3600
        allow_credentials: true
    paths:
        '^/api/':
            origin_regex: true
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
            max_age: 3600